<?xml version="1.0"?>
<package format="3">
  <name>x3plus_mapping_bringup</name>
  <version>0.0.1</version>
  <description>GMapping + reactive navigation bringup for X3 Plus</description>
  <maintainer email="karimnah01@gmail.com">Karim</maintainer>
  <license>MIT</license>

  <!-- Build tool: Python -->
  <buildtool_depend>ament_python</buildtool_depend>
  <buildtool_depend>python3-setuptools</buildtool_depend>

  <!-- Launch + indexing -->
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <!-- Core runtime deps you use -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <!-- External stacks -->
  <exec_depend>ydlidar_ros2_driver</exec_depend>
  <exec_depend>slam_gmapping</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
