/**:
  gripper_group_controller:
    ros__parameters:
      joints: [grip_joint]
      command_interfaces: [position]
      state_interfaces: [position, velocity]
      state_publish_rate: 50
      action_monitor_rate: 20
      allow_partial_joints_goal: true
      constraints:
        goal_time: 0.0
        stopped_velocity_tolerance: 0.02
        grip_joint: {goal: 0.05}
