/**:
  arm_group_controller:
    ros__parameters:
      joints: [arm_joint1, arm_joint2, arm_joint3, arm_joint4, arm_joint5]
      command_interfaces: [position]
      state_interfaces: [position, velocity]
      state_publish_rate: 50
      action_monitor_rate: 20
      allow_partial_joints_goal: true
      constraints:
        goal_time: 0.0
        stopped_velocity_tolerance: 0.02
        arm_joint1: {goal: 0.1}
        arm_joint2: {goal: 0.1}
        arm_joint3: {goal: 0.1}
        arm_joint4: {goal: 0.1}
        arm_joint5: {goal: 0.1}
